name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Sync to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a5c8672c9fe33eaf4fdd0a59d5be43e4
          command: pages deploy . --project-name=newvision --branch=main
